apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-client
  template:
    metadata:
      labels:
        app: ubuntu-client
    spec:
      containers:
      - name: ubuntu-client
        image: ubuntu:latest
        tty: true
        command: ["sleep", "infinity"]
        env:
        - name: ONOS_CONTROLLER_IP
          value: "172.17.0.3"
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-client-service
spec:
  selector:
    app: ubuntu-client
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
  type: ClusterIP

